# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-15 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseslot',
            old_name='timing',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='courseslot',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2018, 4, 15, 22, 22, 3, 35181, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
